### ISSUE TITLE
Problem with SVG on iOS 

### ISSUE THREAD

**Issue by GimazDo** [Kamel-Media/Kamel#91]
Hi, i have the following problem:
I'm trying to draw svg:
```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 200">
<rect width="100%" height="100%" fill="#B68D00"/>
<text x="50%" y="50%" dy="0.36em" text-anchor="middle" pointer-events="none" fill="#ffffff" font-family="'Helvetica', 'Arial', 'Lucida Grande', 'sans-serif'" font-size="125">
T
</text>
</svg>
```

In android it looks:
<img width="38" alt="image" src="https://github.com/Kamel-Media/Kamel/assets/73364856/21a26853-ccbf-49a5-88fa-ce4e8d1f3706">

But in ios:
<img width="33" alt="image" src="https://github.com/Kamel-Media/Kamel/assets/73364856/606eec8c-e1dc-46d1-a046-bd97a54748b0">

How can I solve this problem?
My Kamel config:
```kotlin
KamelConfig {
            httpFetcher(TolkiHttpClientConfiguration.client)
            imageBitmapDecoder()
            imageVectorDecoder()
            svgDecoder()
            imageBitmapCacheSize = DefaultCacheSize
            svgCacheSize = DefaultCacheSize
        }
```
 My code:
 ```kotlin
    CompositionLocalProvider(LocalKamelConfig provides CustomKamelConfig.customKamelConfig) {
        KamelImage(
            resource = asyncPainterResource(Url(avatarUrl)) {
                requestBuilder {
                    cookie("userId", "${getVault().string("Token")}")
                    cacheControl(CacheControl.MAX_AGE)
                }
            },
            contentDescription = "avatar",
            onLoading = { progress -> CircularProgressIndicator(progress) },
            onFailure = { exception ->
                println(exception)
                RemoteImage("${avatarUrl.substringBefore("?etag")}.svg")
            },
            contentScale = ContentScale.Fit,
            modifier = modifier
        )
    }
```

**Comment by luca992** [comment]
So I tried it out and got the same. I don't think I can fix this unfortunately. 

The `loadSvgPainter` implementation for non-jvm targets is basically directly copied from the jvm desktop implementation [here](https://github.com/JetBrains/compose-multiplatform-core/blob/fcaca4dc0666ca101a4d5c8200d9851e3f6cb88d/compose/ui/ui/src/desktopMain/kotlin/androidx/compose/ui/res/DesktopSvgResources.desktop.kt).

However, jvm desktop actually displays that svg just fine. Where as on native I'm seeing `unsupported unit type: <3>` thrown ( I think it's complaining about `dy="0.36em"`) I think the issue is futher upstream with [SVGDOM](https://github.com/JetBrains/skiko/blob/master/skiko/src/commonMain/kotlin/org/jetbrains/skia/svg/SVGDOM.kt). You could try and isolate the issue there and report it... Or you could just try and find another way to center the T in the svg. If all else fails you could make your own `svg` decoder for iOS like the `BatikSvgDecoder` I also have bundled only for jvm desktop
